# Dependencies
# markdown:         redcarpet
highlighter:      pygments

gems: 
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Emily Lewis
tagline:          'Machine Learning for Nuclear Fusion'
description:      'Physics and Machine Learning PhD at UCL'
url:              http://esl-lewis.github.io
baseurl:          /

author:
  name:           'Emily Lewis'
  
twitter:
  username: esllewis
  url:            https://twitter.com/esllewis

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  url:            https://github.com/esl-lewis
  
linkedin: 
  url:            https://www.linkedin.com/in/emilylewis24/
  